### ISSUE TITLE
[질문] docker commit & push 이후 다시 pull 해서 컨테이너를 생성하면 기본 nginx html 이 보입니다.

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/be01-101#34]
# 현상
- docker commit & push 이후 기본 nginx html 이 보입니다.

# 과정
```
$ sudo docker run --name some-nginx-1 \
-p 9051:80 -v /home/nori/code/docker-nginx/html:/usr/share/nginx/html:ro \
-d nginx

$ sudo docker cp index.html some-nginx-1:/usr/share/nginx/html/

$ sudo docker commit pysatellite/myblog:0.1.1

$ sudo docker push  pysatellite/myblog:0.1.1

$ sudo docker run --name some-nginx-2 -p 9052:80 -d pysatellite/myblog:0.1.1
```

**Comment by papercrane55123** [comment]
-v /home/nori/code/docker-nginx/html:/usr/share/nginx/html 옵션은 동적 반응이라 이렇게 생성된 컨테이너를 push하게 되면 /usr/share/nginx/html 안에 내용물은 남아있지 않게 되어 문제가 생기는 것 같습니다

https://docs.docker.com/storage/volumes/

**Comment by INAUGURATE-Ryong** [comment]
commit 후 push하지 않은 상태에서  pull 을 해서 그런것 같습니다~

**Comment by pySatellite** [comment]
> pysatellite/myblog:0.1.1

@INAUGURATE-Ryong 날카로운 지적 감사합니다. 답은 아닌거 같습니다 ^^

**Comment by minu1215** [comment]
복사 후 수정된 파일은 컨테이너 레이어에 저장되지만
이미지 레이어에 있는 파일은 수정이 되지 않는 것 같습니다.

**Comment by jsmin6330** [comment]
저도 어제 찾아봤던 옵션 내용인 것 같은데 ..
아래와 같은 답변을 받긴 했었습니당.
`Docker 컨테이너를 commit하고 Docker Hub에 push할 때, -v (볼륨 마운트) 옵션을 사용하여 컨테이너 내부에 마운트된 디렉토리의 데이터가 컨테이너 이미지에 포함되지 않는다는 점입니다. -v 또는 --volume 옵션을 사용하면, 로컬 파일 시스템의 디렉토리를 컨테이너에 마운트하지만, 이 데이터는 컨테이너의 일시적인 상태에 속하고 이미지의 일부로 commit되지 않습니다.`

-from GPT4 선생님-

**Comment by pySatellite** [comment]
$ sudo docker run --name some-nginx-1 \
-p 9051:80 -v /home/nori/code/docker-nginx/html:/usr/share/nginx/html:ro \
-d nginx

를 아래와 같이 -v 옵션 없이 하시면 될 거 같습니다. 안되면 말씀 주세요 ㅎㅎ

$ sudo docker run --name some-nginx-1 \
-p 9051:80  \
-d nginx

**Comment by jsmin6330** [comment]
- https://github.com/jsmin6330-hello-vue/jsmin6330-hello-vue.github.io/pull/15
위와 같이 시도해봤는데 여전히 되지 않습니다. 도커허브에서 받으면 nginx  파일만 들어간 것으로 확인 됩니다.
`docker pull soominjeong/nginx-gitvlog:0.1.0`

# 최종 시도
- https://github.com/jsmin6330-hello-vue/jsmin6330-hello-vue.github.io/pull/15#issuecomment-1943111113

**Comment by jsmin6330** [comment]
제 fly.io 배포 주소입니당...
https://jsmin6330-hello-vue-github-io.fly.dev/

**Comment by jsmin6330** [comment]
엣지 + 크롬 + 시크릿창까지 캐시의 영향이 있었던 것 같습니다. (시크릿창은 브라우저 캐시 초기화 되는 걸로 아는데 ...) 전체적으로 캐시 다 지우고 컴퓨터 재부팅하니까 배포 사이트 작동합니다... 감사합니다.

![image](https://github.com/beyond-sw-camp/be01-101/assets/150888333/7af61971-85de-4243-af1c-39bf6e0abf50)
