### ISSUE TITLE
[질문] 깃허브 엑션 흉내 ... 잘 안됩니다.

### ISSUE THREAD

**Issue by parc02** [beyond-sw-camp/be01-101#41]
- 아래와 같이 run 했습니다. cron-1 컨테이너에 들어가 보면 아래 Dockerfile 맨 마지막줄 CMD 에서 run 한 cron 및 nginx 가 구동 되지 않았습니다.
```
$ sudo docker run -it -p 8111:80 --name cron-1 0a8eac48314c bash
```

### Dockerfile
```
FROM ubuntu:22.04

RUN apt update
RUN apt install -y nginx
RUN apt install -y git
RUN apt install cron
RUN rm -rf /var/www/html

RUN git clone https://github.com/parc02/parc02.github.io.git /var/www/html

COPY pull.sh /var/www/html/
COPY blog-pull-cronjob /etc/cron.d


RUN crontab /etc/cron.d/blog-pull-cronjob
RUN crontab -l

CMD service cron start;nginx -g 'daemon off;'
```

**Comment by parc02** [comment]
- https://github.com/parc02/parc02.github.io

- 해결 : https://github.com/parc02/parc02.github.io/issues/21#issuecomment-1947705095

**Comment by pySatellite** [comment]
$ sudo docker run -it -p 8111:80 --name cron-1 0a8eac48314c bash
를
$ sudo docker run -d -it -p 8111:80 --name cron-1 0a8eac48314c
이렇게 하시면 될듯 합니다.
