### ISSUE TITLE
[질문] cron이 정상적으로 작동하지 않는 것 같습니다. VS CODE EOL 설정이 이슈

### ISSUE THREAD

**Issue by jsmin6330** [beyond-sw-camp/be01-101#42]
- PR: https://github.com/jsmin6330-hello-vue/jsmin6330-hello-vue.github.io/pull/16
증상: 로그파일이 생기지 않고, 자동 pull이 되지 않습니다.
컨테이너 안에서 nginx는 실행되고 있고,  crontab 리스트가 등록되어 있는 것을 확인했습니다.
git pull도 수동으로 하면 실행이 되고, crontab도 수동으로 실행을 하면 로그 파일이 생깁니다. 

### Dockerfile
```
FROM ubuntu:22.04

RUN apt update
RUN apt install -y nginx
RUN apt install -y git
RUN apt install cron

RUN rm -rf /var/www/html/
RUN git clone https://github.com/jsmin6330-hello-vue/jsmin6330-hello-vue.github.io.git /var/www/html/

COPY pull.sh /var/www/html/
COPY blog-pull-cronjob /etc/cron.d/
RUN crontab /etc/cron.d/blog-pull-cronjob

CMD service cron start;nginx -g 'daemon off;'
```

### pull.sh 
```
#!/bin/bash

echo "start pull-->"
date "+%Y-%m-%d %H:%M:%S"

cd /var/www/html
git pull

echo "<--end pull"
```

### blog-pull-cronjob
```
* * * * * sh /var/www/html/pull.sh >> /var/log/pull.log 2>&1
# new crontab file is missing newline before E0F, can't insta
```ll.

**Comment by pySatellite** [comment]
저도 같은 증상으로 pull.log 가 생성되지 않고 있습니다. 해결 하시는 분에게는 점심을 쏘는 걸로 하겠습니다.

**Comment by jsmin6330** [comment]
제가 파일 편집기로 code (비쥬얼 스튜디오 코드)를 병행해서 사용하는데, 뭔가 파일에 안보이는 영향을 주는 것 같습니다.

테스트해본 결과 code를 중간에 한번이라도 거치는 경우, 마지막 수정이 vi라고 해도 위와 같은 증상이 발생합니다.

**Comment by jsmin6330** [comment]
여러가지 경우의 수를 확인해본 결과, 
Dockerfile만 code를 거치지 않으면 정상 작동합니다.

**Comment by jsmin6330** [comment]
visual studio code 의 경우 기본적으로 EOL 설정이 AUTO로 되어있는데, 리눅스 환경에서 파일을 code로 열었을 때, 아래와 같이 LF로 되어있어도 EOL이 \n으로 반영이 되지 않을 수 있는 것 같습니다.
![image](https://github.com/beyond-sw-camp/be01-101/assets/150888333/57ddf1c9-8ac2-4f2b-9d6b-67ef04d6e3b9)

환경설정에서 EOL을 \n으로 고정시켜 놓고 다시 Dockerfile을 수정한 결과, 이번에는 정상적으로 동작하는 것을 확인했습니다.

https://blog.naver.com/parosaone/222226392378




![image](https://github.com/beyond-sw-camp/be01-101/assets/150888333/5a9c41bd-1645-4fc7-b7c2-c6e38b6ef0ed)
![image](https://github.com/beyond-sw-camp/be01-101/assets/150888333/3d2f21e2-5a15-4dff-b15b-8f0553a92b08)

**Comment by pySatellite** [comment]
해결법까지 찾아 올려주셔서 감사합니다.

![LGTM](https://i.lgtm.fun/2pej.png)
